### ISSUE TITLE
Sort array by key

### ISSUE THREAD

**Issue by Noitidart** [snowcoders/sortier-vscode#222]
I can't figure out how to use this. Is it possible to sort an array based on key?

Example:

```
const pages = [
  {
    contaienrId: '498',
    lazyComponent: () => import('./pages/498.page')
  },
  {
    contaienrId: 'account-overview',
    lazyComponent: () => import('./pages/account/account-overview.page')
  },
  {
    contaienrId: 'edit-password',
    lazyComponent: () => import('./pages/account/edit-password.page')
  },
];
```

I want to sort by key `contaienrId`.

**Comment by k2snowman69** [comment]
Sortier doesn't sort arrays as arrays by definition are ordered lists (item[0], item[1], etc). For example, if an array was defined as:
```
let decreasingValues = [2,1,0];
```
Sorting those values would likely break the code as it's expecting the values in a particular order.

However sortier does sort on objects keys. So if the item being sorted was:
```
{
   "2": undefined,
   "1": undefined,
   "0": undefined,
}
```
This should change to 
```
{
   "0": undefined,
   "1": undefined,
   "2": undefined,
}
```

This is because objects are maps of keys to values. Their order inherently should not matter as it is a list of key value pairs where the value is often looked up by the key, not by the index.

One option to solve your immediate problem would to be to restructure your data so that it's not an array... also by doing this you can decrease your object size by quite a bit:
```
const pageToComponentMap = {
  '498': () => import('./pages/498.page'),
  'account-overview': () => import('./pages/account/account-overview.page'),
  'edit-password': () => import('./pages/account/edit-password.page')
};
```

Hope that helps!

**Comment by Noitidart** [comment]
Thank you very much for such an indepth alternative!
